#----------------------------------------------------------------------
# This file was generated by C:\Python27\Lib\site-packages\wx-2.8-msw-ansi\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

gps_satellites_espace_icone_8581_start_24x24 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAIAAABvFaqvAAAAAXNSR0IArs4c6QAAAAlwSFlz"
    "AAAATwAAAE8BY4r91wAAAAd0SU1FB9wEEQkjAAV1rCAAAAPFSURBVDjLzdTbb9tUHAdwO77H"
    "lyR2mjoXN21S0qbtOmVCqJd13dDoOm3ahBCaKEJoSDzwhvgX+A944BEJITE00CbQVBXWsY1r"
    "u9K16zZgVde0buxcmkvtxHXiW3iYNFjJqgl44PtyjvQ75yP99NM54NTU66qqHJudXdupA/8i"
    "cCwWHx0dudE/MJO8OPnb+j+HtF1NUWuDBw9RlOfa5NXkzLf7nL7U4UUx6mM597lm7YU8DOP3"
    "s6IoESR98tTZjfcGvvrs0zNy8VHZ4vDNob5IOLK0ssYHhY8+GEWKDy78pH3ZufjKxtYT0K5e"
    "V5UqCIKO45RKO00Qw3yBixEEw7HensTIu4MnBvi4R8mnmr/r/SsZ2puvvdCmXGc8APAkhCKQ"
    "bdurqw/zhSIIuio7SrGYc2xzeHjotTfezGTka/Pij0Z2lNyMNFa/Niba2Z4h/x0XoO9pDeL8"
    "AT4YYhiqUlEK20XQ5eqMBs+9evytqfGKeHfu1v0NKV8zoLTGhs20Fze30a7ZhfsHb9zbCwmS"
    "dDtfqDfMUIgPhwKRMP/SiUmGFcTsDln63ltf33FYhgtAGFWomgIsTS9I3dMLLabWXVAA4Oby"
    "i/bAQAJFEBB0beflhgU8FAuEFQubW3FYbAZTfb09i4vkzXtXMnL+QKuBuh4tFEnAEOQ4juPY"
    "+u4uAlpdIU5Sm2ksFSWKFFTHcXzs8JGRiXOhsADsA+m6DoIggiBugmAYBsMJD03ynE9D2mxW"
    "iLF603FKpZKLCE1Mnl47e/KpUCaTAQCApimPzwvChAvGGMYjhNpRjGwEUm4fybFsKMiDAECS"
    "5NjYserb56cT0RYQraqmacEI6jRddrOJIAiKoSTpRhHYQWi1DpimCcMwQRAQBKEoGg4LQkcr"
    "6LBcLm5LdhOo1a02ztfZEeFYluf5dr9HzDZ+vp2raZqczRmGAUOwZdm2Ax56fvjqgcSfU3u8"
    "89bvMFY7Gz8a5DnIBVmW5Xa7RXHrk5nZeKwLwxDDMJaW79YbDQhCTNPO5XKqqrWAPrxwa/DX"
    "xtR5oa+3G8dxwzAURalV1cD62i+los/HdXbF2vzcppjJ57OOA+A4hmFoC+iUWAWAH95PlXRd"
    "Hx8fp2laluX5+fnuvNINKF8Il3uT/c/19OE47vN5JClXrpQbDePxdfCdv31nl6LtyWQyGo2m"
    "0+n+b777a+l6arArnqAoBgRBSc6Wl+aOFspPhfaPwVJz8STn52maXFmeP72a3tvaMwYt144A"
    "C1cSCcbn17Td/Vp7xlzm/S/niv8B1PqJ/I+gPwBk05eOQBb9ZgAAAABJRU5ErkJggg==")
getgps_satellites_espace_icone_8581_start_24x24Data = gps_satellites_espace_icone_8581_start_24x24.GetData
getgps_satellites_espace_icone_8581_start_24x24Image = gps_satellites_espace_icone_8581_start_24x24.GetImage
getgps_satellites_espace_icone_8581_start_24x24Bitmap = gps_satellites_espace_icone_8581_start_24x24.GetBitmap

